function man(num) {
    var { tiaoSheng, tiaoYuan, shiXinQiu } = input();
    if (tiaoSheng >= 185)
        var tiaoShengPoints = 20
    else if (tiaoSheng >= 170)
        var tiaoShengPoints = 19
    else if (tiaoSheng >= 155)
        var tiaoShengPoints = 18
    else if (tiaoSheng >= 140)
        var tiaoShengPoints = 17
    else if (tiaoSheng >= 132)
        var tiaoShengPoints = 16
    else if (tiaoSheng >= 124)
        var tiaoShengPoints = 15
    else if (tiaoSheng >= 116)
        var tiaoShengPoints = 14
    else if (tiaoSheng >= 108)
        var tiaoShengPoints = 13
    else if (tiaoSheng >= 100)
        var tiaoShengPoints = 12
    else if (tiaoSheng >= 92)
        var tiaoShengPoints = 11
    else if (tiaoSheng >= 84)
        var tiaoShengPoints = 10
    else if (tiaoSheng >= 76)
        var tiaoShengPoints = 9
    else if (tiaoSheng >= 68)
        var tiaoShengPoints = 8
    else if (tiaoSheng >= 60)
        var tiaoShengPoints = 7
    else if (tiaoSheng >= 52)
        var tiaoShengPoints = 6
    else if (tiaoSheng >= 44)
        var tiaoShengPoints = 5
    else if (tiaoSheng >= 36)
        var tiaoShengPoints = 4
    else if (tiaoSheng >= 28)
        var tiaoShengPoints = 3
    else if (tiaoSheng >= 20)
        var tiaoShengPoints = 2
    else if (tiaoSheng >= 12)
        var tiaoShengPoints = 1
    else var tiaoShengPoints = 0
    if (tiaoYuan >= 2.4)
        var tiaoYuanPoints = 15
    else if (tiaoYuan >= 2.34)
        var tiaoYuanPoints = 14
    else if (tiaoYuan >= 2.28)
        var tiaoYuanPoints = 13
    else if (tiaoYuan >= 2.22)
        var tiaoYuanPoints = 12
    else if (tiaoYuan >= 2.16)
        var tiaoYuanPoints = 11
    else if (tiaoYuan >= 2.1)
        var tiaoYuanPoints = 10
    else if (tiaoYuan >= 2.04)
        var tiaoYuanPoints = 9
    else if (tiaoYuan >= 1.98)
        var tiaoYuanPoints = 8
    else if (tiaoYuan >= 1.92)
        var tiaoYuanPoints = 7
    else if (tiaoYuan >= 1.86)
        var tiaoYuanPoints = 6
    else if (tiaoYuan >= 1.8)
        var tiaoYuanPoints = 5
    else if (tiaoYuan >= 1.74)
        var tiaoYuanPoints = 4
    else if (tiaoYuan >= 1.68)
        var tiaoYuanPoints = 3
    else if (tiaoYuan >= 1.62)
        var tiaoYuanPoints = 2
    else if (tiaoYuan >= 1.56)
        var tiaoYuanPoints = 1
    else var tiaoYuanPoints = 0
    if (shiXinQiu >= 9.7)
        var shiXinQiuPoints = 15
    else if (shiXinQiu >= 9.3)
        var shiXinQiuPoints = 14
    else if (shiXinQiu >= 8.9)
        var shiXinQiuPoints = 13
    else if (shiXinQiu >= 8.5)
        var shiXinQiuPoints = 12
    else if (shiXinQiu >= 8.1)
        var shiXinQiuPoints = 11
    else if (shiXinQiu >= 7.7)
        var shiXinQiuPoints = 10
    else if (shiXinQiu >= 7.3)
        var shiXinQiuPoints = 9
    else if (shiXinQiu >= 6.9)
        var shiXinQiuPoints = 8
    else if (shiXinQiu >= 6.5)
        var shiXinQiuPoints = 7
    else if (shiXinQiu >= 6.1)
        var shiXinQiuPoints = 6
    else if (shiXinQiu >= 5.7)
        var shiXinQiuPoints = 5
    else if (shiXinQiu >= 5.3)
        var shiXinQiuPoints = 4
    else if (shiXinQiu >= 4.8)
        var shiXinQiuPoints = 3
    else if (shiXinQiu >= 4.3)
        var shiXinQiuPoints = 2
    else if (shiXinQiu >= 3.8)
        var shiXinQiuPoints = 1
    else var shiXinQiuPoints = 0
    var sum = Math.trunc(tiaoShengPoints) + Math.trunc(tiaoYuanPoints) + Math.trunc(shiXinQiuPoints);
    alert("你的分数为：" + sum)
}

function woman(num) {
    var { tiaoSheng, tiaoYuan, shiXinQiu } = input();
    if (tiaoSheng >= 185)
        var tiaoShengPoints = 20
    else if (tiaoSheng >= 170)
        var tiaoShengPoints = 19
    else if (tiaoSheng >= 155)
        var tiaoShengPoints = 18
    else if (tiaoSheng >= 140)
        var tiaoShengPoints = 17
    else if (tiaoSheng >= 132)
        var tiaoShengPoints = 16
    else if (tiaoSheng >= 124)
        var tiaoShengPoints = 15
    else if (tiaoSheng >= 116)
        var tiaoShengPoints = 14
    else if (tiaoSheng >= 108)
        var tiaoShengPoints = 13
    else if (tiaoSheng >= 100)
        var tiaoShengPoints = 12
    else if (tiaoSheng >= 92)
        var tiaoShengPoints = 11
    else if (tiaoSheng >= 84)
        var tiaoShengPoints = 10
    else if (tiaoSheng >= 76)
        var tiaoShengPoints = 9
    else if (tiaoSheng >= 68)
        var tiaoShengPoints = 8
    else if (tiaoSheng >= 60)
        var tiaoShengPoints = 7
    else if (tiaoSheng >= 52)
        var tiaoShengPoints = 6
    else if (tiaoSheng >= 44)
        var tiaoShengPoints = 5
    else if (tiaoSheng >= 36)
        var tiaoShengPoints = 4
    else if (tiaoSheng >= 28)
        var tiaoShengPoints = 3
    else if (tiaoSheng >= 20)
        var tiaoShengPoints = 2
    else if (tiaoSheng >= 12)
        var tiaoShengPoints = 1
    else var tiaoShengPoints = 0
    if (tiaoYuan >= 2.03)
        var tiaoYuanPoints = 15
    else if (tiaoYuan >= 1.97)
        var tiaoYuanPoints = 14
    else if (tiaoYuan >= 1.91)
        var tiaoYuanPoints = 13
    else if (tiaoYuan >= 1.85)
        var tiaoYuanPoints = 12
    else if (tiaoYuan >= 1.79)
        var tiaoYuanPoints = 11
    else if (tiaoYuan >= 1.73)
        var tiaoYuanPoints = 10
    else if (tiaoYuan >= 1.67)
        var tiaoYuanPoints = 9
    else if (tiaoYuan >= 1.61)
        var tiaoYuanPoints = 8
    else if (tiaoYuan >= 1.55)
        var tiaoYuanPoints = 7
    else if (tiaoYuan >= 1.49)
        var tiaoYuanPoints = 6
    else if (tiaoYuan >= 1.43)
        var tiaoYuanPoints = 5
    else if (tiaoYuan >= 1.37)
        var tiaoYuanPoints = 4
    else if (tiaoYuan >= 1.31)
        var tiaoYuanPoints = 3
    else if (tiaoYuan >= 1.25)
        var tiaoYuanPoints = 2
    else if (tiaoYuan >= 1.19)
        var tiaoYuanPoints = 1
    else var tiaoYuanPoints = 0
    if (shiXinQiu >= 6.5)
        var shiXinQiuPoints = 15
    else if (shiXinQiu >= 6.2)
        var shiXinQiuPoints = 14
    else if (shiXinQiu >= 5.9)
        var shiXinQiuPoints = 13
    else if (shiXinQiu >= 5.6)
        var shiXinQiuPoints = 12
    else if (shiXinQiu >= 5.3)
        var shiXinQiuPoints = 11
    else if (shiXinQiu >= 5.1)
        var shiXinQiuPoints = 10
    else if (shiXinQiu >= 4.9)
        var shiXinQiuPoints = 9
    else if (shiXinQiu >= 4.6)
        var shiXinQiuPoints = 8
    else if (shiXinQiu >= 4.3)
        var shiXinQiuPoints = 7
    else if (shiXinQiu >= 4.0)
        var shiXinQiuPoints = 6
    else if (shiXinQiu >= 3.7)
        var shiXinQiuPoints = 5
    else if (shiXinQiu >= 3.4)
        var shiXinQiuPoints = 4
    else if (shiXinQiu >= 3.1)
        var shiXinQiuPoints = 3
    else if (shiXinQiu >= 2.9)
        var shiXinQiuPoints = 2
    else if (shiXinQiu >= 2.7)
        var shiXinQiuPoints = 1
    else var shiXinQiuPoints = 0
    var sum = Math.trunc(tiaoShengPoints) + Math.trunc(tiaoYuanPoints) + Math.trunc(shiXinQiuPoints);
    alert("你的分数为：" + sum)
}

function input() {
    var tiaoSheng = prompt("跳绳（个）");
    var tiaoYuan = prompt("立定跳远（米）");
    var shiXinQiu = prompt("实心球（米）");
    return { tiaoSheng, tiaoYuan, shiXinQiu };
}
